### ISSUE TITLE
Using the library

### ISSUE THREAD

**Issue by AMDelo** [ggravlingen/pyesef#254]
Hello! This library has the potential of being very useful, nicely done!

I am trying to use it but I am stuck. I have XBRL reports in .zip format in an 'archive' folder, but can you provide a bit more details on exactly how we can use the library to export the results? I tried to run it but it seems that it always finds 0 files, even if I place the files in an archives folder.

**Comment by ggravlingen** [comment]
Thank you for your feedback!

I updated the readme with some additional information. In case it still doesn't work, can you please provide me with a link to the file you're trying to parse (if it's in the public domain)?
